// <auto-generated />
using MVCProject.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCProject.Migrations
{
    [DbContext(typeof(ProductReviewContext))]
    [Migration("20230803173728_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCProject.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The world of Elden Ring is called the Lands Between – a large realm ruled by demigods and blessed by the power of the Elden Ring and the Erdtree. A meme that you might have seen doing the rounds joked that Elden Ring is in fact set in the US state of Ohio, but, unsurprisingly, this is false. The lands of the Lands Between are simply one giant, mystical continent surrounded by water. We’ve found the Elden Ring map fragments, so take a look to get the lay of the land.",
                            Image = "https://th.bing.com/th/id/OIP.HERMAyUVzo3DzgckW79BCAHaDz?w=340&h=179&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            Name = "Elden Ring"
                        },
                        new
                        {
                            Id = 2,
                            Description = "America, 1899.\r\nArthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive",
                            Image = "https://th.bing.com/th/id/OIP.MUqc73udKVBorlv2f2VK7gHaEK?w=280&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            Name = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "In the enchanting world of Hyrule, a courageous young hero named Link sets out on an epic quest to rescue Princess Zelda from the clutches of the evil sorcerer Ganon. With the power of the Triforce guiding him, Link must navigate treacherous dungeons, solve intricate puzzles, and face formidable foes to restore peace to the land. This timeless tale of bravery, friendship, and adventure has captivated players for generations, making \"The Legend of Zelda\" a beloved and iconic video game series.",
                            Image = "https://th.bing.com/th/id/OIP.y1CgDIrbI1bS1MfB5Ls5nQHaEo?w=284&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            Name = "The Legend of Zelda"
                        },
                        new
                        {
                            Id = 4,
                            Description = "\r\nIn \"Flappy Bird,\" embark on a simple yet addictively challenging journey through the skies. Play as a tiny, determined bird, and with just a tap, guide it through narrow gaps between green pipes. Dodge obstacles, test your reflexes, and try to achieve the highest score possible. With its minimalist design and easy-to-learn gameplay, \"Flappy Bird\" offers endless hours of fun and frustration as players strive for mastery in this mobile gaming sensation.",
                            Image = "https://th.bing.com/th/id/OIP.VUwmSfhAI_28Hb6fjU2dZAHaEo?w=265&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            Name = "Flappy Bird"
                        });
                });

            modelBuilder.Entity("MVCProject.Models.ReviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("StarRating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Elden Ring is an overhyped and convoluted mess that fails to deliver on its promises, leaving players with a tedious and disappointing experience.",
                            Name = "Rackean Roberts",
                            ProductId = 1,
                            Rating = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Elden Ring is an awe-inspiring masterpiece that seamlessly blends the hauntingly beautiful world, captivating lore, and challenging gameplay, creating an unforgettable experience for any adventurous soul",
                            Name = "Vance Winters",
                            ProductId = 1,
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            Content = "Flappy Bird is an addictive and exhilarating mobile game that keeps me endlessly entertained with its simple yet challenging gameplay!",
                            Name = "Joseph Camacho",
                            ProductId = 4,
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            Content = "Red Dead Redemption 2 is an absolute masterpiece, seamlessly blending a breathtaking open-world, deeply immersive storytelling, and an unparalleled level of attention to detail that keeps me coming back for more adventures in the Old West.",
                            Name = "Christina Exclusa",
                            ProductId = 2,
                            Rating = 5
                        },
                        new
                        {
                            Id = 5,
                            Content = "The Legend of Zelda series is an unparalleled gaming experience that weaves together breathtaking adventures, clever puzzles, and a timeless charm, leaving me utterly spellbound and forever in awe of its magical world.",
                            Name = "Jatin Patel",
                            ProductId = 3,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("MVCProject.Models.ReviewModel", b =>
                {
                    b.HasOne("MVCProject.Models.ProductModel", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MVCProject.Models.ProductModel", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
